### ISSUE TITLE
Edits and changes made to the content 

### ISSUE THREAD

**Issue by vsharma2288** [pupilfirst/ev101-scripts#2]
- [x] Reviewed all content for language and grammatical issues 
- [x] Made necessary changes in the content at required places
- [x] Fixed Header tag issues in the markdown, followed # for heading1 and ## for rest of the headings
- [x] Fixed caption issues in the videos on LMS 
- [x] Fixed interactivity issues in the LMS videos

**Comment by reenas** [comment]
This is done, closing the issue.
